import type { LucideIcon } from 'lucide-react';
import {
    Activity,
    Bell,
    BellRing,
    BookOpen,
    Calculator,
    Calendar,
    CheckSquare,
    ClipboardCheck,
    Feather,
    FileText,
    FolderKanban,
    FolderOpen,
    GraduationCap,
    Key,
    Layers,
    LayoutDashboard,
    LayoutGrid,
    Lock,
    Mail,
    MailCheck,
    MessageCircle,
    MessageSquare,
    MonitorPlay,
    Package,
    Palette,
    Puzzle,
    Receipt,
    Server,
    Settings,
    Shield,
    ShieldCheck,
    Store,
    UserCheck,
    UserPlus,
    Users,
    Video,
    Wifi,
    Zap,
} from 'lucide-react';

export const iconMap: Record<string, LucideIcon> = {
    Activity,
    Bell,
    BellRing,
    LayoutGrid,
    LayoutDashboard,
    FolderKanban,
    FolderOpen,
    CheckSquare,
    Feather,
    Lock,
    FileText,
    Settings,
    Server,
    Users,
    ShieldCheck,
    Puzzle,
    Mail,
    MailCheck,
    Shield,
    Palette,
    MessageSquare,
    MessageCircle,
    Package,
    Calendar,
    Receipt,
    Calculator,
    Store,
    GraduationCap,
    BookOpen,
    MonitorPlay,
    Video,
    ClipboardCheck,
    Layers,
    Wifi,
    Key,
    UserCheck,
    UserPlus,
    Zap,
    text: FileText,
    video: Video,
    quiz: ClipboardCheck,
    check: CheckSquare,
};

export const DEFAULT_ICON = Puzzle;
